### ISSUE TITLE
Terminer la conception du stockage

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#1]
Me rendre ici:
votre nom prénom
le lien vers votre projet sous github

**Comment by yamineben** [comment]
BENMESSAOUD Yamine

https://github.com/yamineben/GL51-TD1.git

**Comment by stanicchris** [comment]
STANIC-PAGANO Christopher

https://github.com/stanicchris/Projet_GL51.git

**Comment by patricke25** [comment]
PEGON Sylvain
https://github.com/patricke25/GL51_TD1.git

**Comment by Grudging7645** [comment]
BONNETAIN Camille
https://github.com/camille-bonnetain/gl51_td1.git

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie

https://github.com/PmRay/gl51

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
https://github.com/nzodalandry/GL51_PROJECT_TD1

**Comment by CharlotteYU** [comment]
Shijia YU
https://github.com/CharlotteYU/GL51/tree/master/GL51TD/GL51-TD1-ShijiaYU

**Comment by ElomKossi** [comment]
KOSSI Elom 

https://github.com/ElomKossi/GL51.P2020.git

**Comment by duclouxSamuel** [comment]
DUCLOUX Samuel

https://github.com/duclouxSamuel/gl51

**Comment by Hawlink** [comment]
SIDAWY Cem
https://github.com/Hawlink/GL51TD1

**Comment by desperadooo** [comment]
ZHENG Huangkai
https://github.com/desperadooo/GL51_TD1

**Comment by jinhogate** [comment]
kossi GBEGNON
https://github.com/jinhogate/p2020.git

**Comment by HaoyunLIAO** [comment]
LIAO Haoyun
https://github.com/HaoyunLIAO/GL51_TD1

**Comment by AntoineYu** [comment]
YU ZhenQing
https://github.com/AntoineYu/GL51_TD1

**Comment by MaoJiawei97** [comment]
Mao jiawei
https://github.com/MaoJiawei97/GL51

**Comment by zhuoli-wu** [comment]
WU Zhuoli
https://github.com/zhuoli-wu/GL51_TD1

**Comment by EleryanYuri** [comment]
Aurélien Saunier
https://github.com/EleryanYuri/GL51_TD1.git

**Comment by kAgotsi** [comment]
AGOTSI Gédéon
https://github.com/kAgotsi/gl51-tp1.

**Comment by Zechirine** [comment]
NOUASSI Zechirine
https://github.com/Zechirine/GL51_P2020.git

**Comment by Gresefo** [comment]
MARTIN Loïc
https://github.com/Gresefo/GL51-TD1-Photo.git

**Comment by bdaris** [comment]
Nanjeu Borel
https://github.com/bdaris/GL51Groovy/tree/master/p2020

**Comment by YvetteMiao** [comment]
Yiwen Miao
https://github.com/YvetteMiao/gl51_tp1
