### ISSUE TITLE
Lancer une merge request et participer à une autre merge request

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#4]
Ouvrir une merge request sur le repository d'un de vos camarades en proposant des améliorations sur le devoir de la semaine dernière.

Prendre une des merges requests proposées et la commenter pour proposer une amélioration.

Poster ici les urls de votre merge request de celle de vos commentaires ainsi que le nom/prenom

Attention ne pas accepte les MR des autres.

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie

https://github.com/CharlotteYU/GL51/pull/1

**Comment by patricke25** [comment]
PEGON Sylvain
Reponse à la pull request de Yamine Benmessaoud sur mon travail : https://github.com/patricke25/GL51_TD1/pull/1
Ma pull request sur le projet de Samuel DUCLOUX 👍 https://github.com/duclouxSamuel/gl51/pull/1

**Comment by yamineben** [comment]
BENMESSAOUD Yamine
Pull request proposé à Sylvain PEGON :  https://github.com/patricke25/GL51_TD1/pull/1
Review de la pull request qui m'a été proposée : https://github.com/yamineben/GL51-TD1/pull/1#pullrequestreview-378698048

**Comment by CharlotteYU** [comment]
Shijia YU
Reponse à la pull request de FANTCHENOU Pierre-Marie sur mon travail : CharlotteYU/GL51#1
Pull request proposé à Yiwen MIAO : https://github.com/YvetteMiao/gl51_tp1/pull/1

**Comment by YvetteMiao** [comment]
Yiwen Miao
Reponse à la pull request de Shijia YU sur mon travail : https://github.com/YvetteMiao/gl51_tp1/pull/1
Pull request proposé à Shijia YU : https://github.com/CharlotteYU/GL51/pull/3

**Comment by jinhogate** [comment]
Kossi GBEGNON
Pull request proposé sur le repo de Gedeon AGOTSI: 
https://github.com/kAgotsi/gl51-tp1/pull/1#issue-391896172
Comment sur une pull request proposée:
https://github.com/kAgotsi/gl51-tp1/pull/1#discussion_r396018171

**Comment by stanicchris** [comment]
Christopher STANIC-PAGANO
Réponse à la pull request de Aurélien SAUNIER sur mon travail : https://github.com/stanicchris/Projet_GL51/pull/1
Pull request proposé à Aurélien SAUNIER : https://github.com/EleryanYuri/GL51_TD1/pull/1

**Comment by EleryanYuri** [comment]
Aurélien Saunier
Pull request sur le repo de STANIC-PAGANO Christopher
https://github.com/stanicchris/Projet_GL51/pull/1
Commentaire sur une pull request proposée :
https://github.com/EleryanYuri/GL51_TD1/pull/1

**Comment by desperadooo** [comment]
ZHENG Huangkai
Pull request sur le repo de LIAO Haoyun : https://github.com/HaoyunLIAO/GL51_TD1/pull/1#event-3164855811
Commentaire sur une pull request proposé : https://github.com/desperadooo/GL51_TD1/pull/1

**Comment by HaoyunLIAO** [comment]
LIAO Haoyun
Pull request sur le repo de ZHENG Huangkai : https://github.com/desperadooo/GL51_TD1/pull/1
Commentaire sur une pull request proposé : https://github.com/HaoyunLIAO/GL51_TD1/pull/1

**Comment by Gresefo** [comment]
Loïc MARTIN
Pull request sur le dépôt de Cem Sidawy : https://github.com/Hawlink/GL51TD1/pull/1
Commentaire sur une pull request proposée : https://github.com/stanicchris/Projet_GL51/pull/1/files

**Comment by Hawlink** [comment]
Cem SIDAWY
Pull request sur le dépôt de Loïc Martin : https://github.com/Gresefo/GL51-TD1-Photo/pull/1
Commentaire sur une pull request proposée : https://github.com/Hawlink/GL51TD1/pull/1#discussion_r398663029

**Comment by AntoineYu** [comment]
Yu ZhenQing
Pull request sur le repo de MAO JiaWei : https://github.com/MaoJiawei97/GL51/pull/1
Commentaire sur une pull request proposé : https://github.com/AntoineYu/GL51_TD1/pull/1

**Comment by ElomKossi** [comment]
Elom KOSSI

Pull request proposé à Kossi GBEGNON https://github.com/jinhogate/p2020/pull/1

**Comment by Zechirine** [comment]
NOUASSI Zechirine

Pull request proposé à Elom KOSSI https://github.com/ElomKossi/GL51.P2020/pull/1

**Comment by ZilinGUO** [comment]
ZILIN GUO
Pull request sur le repo de  YU Zhengqing : https://github.com/AntoineYu/GL51_TD1
Commentaire sur une pull request proposé : https://github.com/ZilinGUO/gl51/pull/1

**Comment by zhuoli-wu** [comment]
Wu Zhuoli 
Pull request sur le repo de YU Zhengqing: https://github.com/AntoineYu/GL51_TD1/pull/2

**Comment by duclouxSamuel** [comment]
DUCLOUX Samuel

Pull request sur le repo de Sylvain Pegon : https://github.com/patricke25/GL51_TD1/pull/2
Commentaire sur sa pull request : https://github.com/duclouxSamuel/gl51/pull/1

**Comment by Grudging7645** [comment]
Camille BONNETAIN

Pull request sur le repo de Sylvain PEGON : https://github.com/patricke25/GL51_TD1/pull/3
Commentaire sur une pull request proposé : https://github.com/stanicchris/Projet_GL51/pull/1/files

**Comment by kAgotsi** [comment]
Gédéon AGOTSI

Pull request sur le repo de Kossi GBEGNON :  https://github.com/jinhogate/p2020/pull/2
Pull request qu'il m'a proposé  : https://github.com/kAgotsi/gl51-tp1/pull/1

**Comment by nzodalandry** [comment]
Landry NZODA OUMBE

Pull request sur le travail de Borel Daris NANJEU : https://github.com/bdaris/GL51Groovy/pull/1
Commentaire sur une pull request proposée : https://github.com/jinhogate/p2020/pull/2#issuecomment-604931266

**Comment by bdaris** [comment]
Pull request sur la repo de Landry Nzoda OUMBE: https://github.com/nzodalandry/GL51_PROJECT_TD1/pull/1

**Comment by LPA2-Automne2016** [comment]
Bien joué, vous vous êtes visiblement fait plaisir, c'est bien.
