### ISSUE TITLE
Mettre en place l'intégration continue et mocker le MovieClient

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#5]
1 mettre en place l'intégration continue:
https://github.com/LPA2-Automne2016/gl51-P2020/blob/master/.github/workflows/blank.yml
2 Mocker l'appel au movie client:
https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html
https://docs.google.com/presentation/d/1bGsRlQvYqSKIG-bPmhoiwupZ3lBpfWdHTGhejTwj26k/edit#slide=id.g521244029b_0_14
http://spockframework.org/spock/docs/1.0/interaction_based_testing.html

Poster:
- nom prénom
-  le lien vers le resultat du test dans github ( exemple: https://github.com/LPA2-Automne2016/gl51-P2020/actions/runs/64742007 )
- le lien vers votre classe de test: 
https://github.com/LPA2-Automne2016/gl51-P2020/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by yamineben** [comment]
BENMESSAOUD Yamine

Résultat du test : https://github.com/yamineben/GL51-TD3/actions/runs/64845980
Classe de test ; https://github.com/yamineben/GL51-TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by AntoineYu** [comment]
Yu ZhenQing
Résultat du test : https://github.com/AntoineYu/GL51_TD3/actions/runs/69088777
Classe de test : https://github.com/AntoineYu/GL51_TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by YvetteMiao** [comment]
YiWen Miao
Résultat du test : https://github.com/YvetteMiao/tp3/actions/runs/69131219
Classe de test : https://github.com/YvetteMiao/tp3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by ZilinGUO** [comment]
ZILIN GUO
Résultat du test : https://github.com/ZilinGUO/GL51_TD3/actions/runs/69171728
Classe de test : https://github.com/ZilinGUO/GL51_TD3/blob/master/src/test/groovy/gl/td3/movie/service/Impl/MovieRegistryImplTest.groovy

**Comment by EleryanYuri** [comment]
Aurélien Saunier
Intégration continue : 
https://github.com/EleryanYuri/GL51_TD1/actions/runs/69205790
Classe de test : 
https://github.com/EleryanYuri/GL51_TD1/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by CharlotteYU** [comment]
Shijia YU
Résultat du test : https://github.com/CharlotteYU/GL51TD/actions/runs/69031022
Classe de test : https://github.com/CharlotteYU/GL51TD/blob/master/src/test/groovy/gl51/Movie/service/impl/MovieClientImplTest.groovy

Update:  04/04/2020
J'ai suivi votre correction de cours vendredi mais toujours eu une fault de MockBean 
io.micronaut.context.exceptions.BeanContextException: Unexpected error loading bean definition [gl51.$Movie.service.impl.$MovieRegistryImplTest$MovieClient0Definition$InterceptedDefinition]: failed to access class gl51.Movie.service.impl.$MovieRegistryImplTest$MovieClient0Definition$Intercepted from class gl51.$Movie.service.impl.$MovieRegistryImplTest$MovieClient0Definition$InterceptedDefinitionClass (gl51.Movie.service.impl.$MovieRegistryImplTest$MovieClient0Definition$Intercepted and gl51.$Movie.service.impl.$MovieRegistryImplTest$MovieClient0Definition$InterceptedDefinitionClass are in unnamed module of loader 'app')
Est-ce que vous pouvez regarder pour moi ?

Update:09/04/2020
Probleme resoudu

**Comment by desperadooo** [comment]
ZHENG Huangkai
Résultat du test : https://github.com/desperadooo/GL51_TD3/actions/runs/69180550
Classe de test : https://github.com/desperadooo/GL51_TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by duclouxSamuel** [comment]
DUCLOUX Samuel

Résultat du test : https://github.com/duclouxSamuel/gl51/actions/runs/69240892
Classe de test : https://github.com/duclouxSamuel/gl51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by patricke25** [comment]
PEGON Sylvain

Résultat du test : https://github.com/patricke25/GL51_TD1/actions/runs/69303447
Classe de test : 
https://github.com/patricke25/GL51_TD1/blob/master/src/test/groovy/gl51/movie/service/Impl/ServiceImplTest.groovy

**Comment by stanicchris** [comment]
STANIC-PAGANO Christopher
Résultat du test : https://github.com/stanicchris/Projet_GL51/runs/556111160
Classe de test : https://github.com/stanicchris/Projet_GL51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by Grudging7645** [comment]
BONNETAIN Camille
Résultat du test : https://github.com/camille-bonnetain/gl51/actions/runs/69386031
Classe de test : 
https://github.com/camille-bonnetain/gl51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by zhuoli-wu** [comment]
WU Zhuoli
Résultat du test : https://github.com/zhuoli-wu/GL51_TD2/actions/runs/66679598
Classe de test :
https://github.com/zhuoli-wu/GL51_TD2/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by kAgotsi** [comment]
Gédéon AGOTSI
Résultat du test : https://github.com/kAgotsi/gl51-tp1/runs/556849623
Classe de test : https://github.com/kAgotsi/gl51-tp1/blob/master/src/main/java/gl51/tp1/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by ElomKossi** [comment]
Elom KOSSI

Résultat du test: https://github.com/ElomKossi/GL51.P2020/runs/539936617
Classe de test: https://github.com/ElomKossi/GL51.P2020/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie
Resultat du Test : https://github.com/PmRay/gl51/actions/runs/69702314

Classe de Test: https://github.com/PmRay/gl51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy

https://github.com/PmRay/gl51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by Hawlink** [comment]
SIDAWY Cem
Résultat du test : https://github.com/Hawlink/GL51TD1/actions/runs/69736125
Classe de test : https://github.com/Hawlink/GL51TD1/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by HaoyunLIAO** [comment]
LIAO Haoyun
Résultat du test : 
https://github.com/HaoyunLIAO/GL51-TD3/actions/runs/69820987
Classe de test :
https://github.com/HaoyunLIAO/GL51-TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
Résultat du test :
https://github.com/nzodalandry/GL51_PROJECT_TD3/actions/runs/69851466
Classe de test :
https://github.com/nzodalandry/GL51_PROJECT_TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by bdaris** [comment]
NANJEU Borel Daris
integration continue:
https://github.com/bdaris/GL51Groovy/actions/runs/69899240

classe test:
https://github.com/bdaris/GL51Groovy/blob/master/p2020/src/test/groovy/gl51/movie/service/Impl/MovieRegistryImplTest.groovy

**Comment by LPA2-Automne2016** [comment]
debut du cours

**Comment by jinhogate** [comment]
Kossi GBEGNON
Résultat du test:
https://github.com/jinhogate/p2020/actions/runs/70672450

Classe de test:
https://github.com/jinhogate/p2020/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by ZhanKanyun** [comment]
ZHAN Kanyun
Résultat du test:
https://github.com/ZhanKanyun/GL51_TD3/actions/runs/69879403

classe test:
https://github.com/ZhanKanyun/GL51_TD3/blob/master/GL51_TD3/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by BaiYuhaoSpiceeYJ** [comment]
BAI YUHAO
Résultat du test : https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/actions/runs/70021227
Classe de test : https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by BaiYuhaoSpiceeYJ** [comment]
BAI YUHAO (update)
Résultat du test : https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/actions/runs/70043707
Classe de test : https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy
 Comment: I have retried to build this project in action and it works this time.

**Comment by ZhanKanyun** [comment]
ZHAN Kanyun
Résultat du test:
https://github.com/ZhanKanyun/TD3_GL51/actions/runs/70047169

classe test:
https://github.com/ZhanKanyun/TD3_GL51/blob/master/src/test/groovy/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by Gresefo** [comment]
Loïc MARTIN
Résultat du test:
https://github.com/Gresefo/GL51-TD3/actions/runs/71123380
(quand je lance les tests depuis IntelliJ, j'ai aussi 5 failed et 0 passed, les injects semblent poser problèmes)

classe test:
https://github.com/Gresefo/GL51-TD3/blob/master/src/test/groovy/test/gl51/movie/service/impl/MovieClientImplTest.groovy

**Comment by MaoJiawei97** [comment]
Mao Jiawei
Résultat du test:https://github.com/MaoJiawei97/GL51_TD4/actions/runs/74398271

classe test
https://github.com/MaoJiawei97/GL51_TD4/blob/master/src/test/groovy/gl51/td3/movie/service/impl/MovieRegistryImplTest.groovy

**Comment by Zechirine** [comment]
NOUASSI Zechirine
Résultat du test :https://github.com/Zechirine/GL51_p20/actions/runs/74744205

classe test
https://github.com/Zechirine/GL51_p20/blob/master/src/test/groovy/gl51/movie/service/impl/MovieRegistryImplTest.groovy
