### ISSUE TITLE
Mettre en place le controlleur de films

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#7]
Créer et modifier le controlleur existant pour:

- intégrer le mock du MovieClient
- tester que l'ajout d'un movie via le POST le fait bien apparaitre dans la liste des favoris.
- ouvrir une merge request pour merger votre code dans master ( attention à bien travailler sur une branche)

Me rendre le lien vers votre merge request

**Comment by LPA2-Automne2016** [comment]
exemple de ce que je veux obtenir
https://github.com/LPA2-Automne2016/gl51-P2020/pull/6

**Comment by patricke25** [comment]
PEGON Sylvain
Merge request : https://github.com/patricke25/GL51_TD1/pull/5
MovieControler : https://github.com/patricke25/GL51_TD1/blob/MoovieClient/src/main/groovy/gl51/MovieController.groovy
MovieControlerSpec :https://github.com/patricke25/GL51_TD1/blob/MoovieClient/src/test/groovy/gl51/MovieControllerSpec.groovy

**Comment by AntoineYu** [comment]
Yu ZhenQing
Merge request: https://github.com/AntoineYu/GL51_TD4/pull/1

**Comment by CharlotteYU** [comment]
Shijia YU
Merge request : https://github.com/CharlotteYU/GL51TD/pull/1

**Comment by ZilinGUO** [comment]
GUO Zilin
Merge request : https://github.com/ZilinGUO/GL51_TD4/pull/1

**Comment by zhuoli-wu** [comment]
WU Zhuoli
Merge request : https://github.com/zhuoli-wu/GL51_TD2/pull/1

**Comment by Hawlink** [comment]
SIDAWY Cem
Merge request : https://github.com/Hawlink/GL51TD1/pull/2

**Comment by desperadooo** [comment]
ZHENG Huangkai
Merge request : Merge request :https://github.com/desperadooo/GL51_TD3/pull/2

**Comment by duclouxSamuel** [comment]
Ducloux Samuel

[Merge Request](https://github.com/duclouxSamuel/gl51/pull/2)

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie
Merge Request : https://github.com/PmRay/gl51/pull/1

**Comment by stanicchris** [comment]
STANIC-PAGANO Christopher
Merge request : https://github.com/stanicchris/Projet_GL51/pull/3

**Comment by Grudging7645** [comment]
BONNETAIN Camille
Merge request : https://github.com/camille-bonnetain/gl51/pull/2

**Comment by YvetteMiao** [comment]
Yiwen Miao
Merge request :https://github.com/YvetteMiao/p2020/pull/1

**Comment by MaoJiawei97** [comment]
Mao Jiawei
Merge request:https://github.com/MaoJiawei97/GL51_TD4/pull/1

**Comment by EleryanYuri** [comment]
Aurélien Saunier
Merge request : https://github.com/EleryanYuri/GL51_TD1/pull/2

**Comment by ElomKossi** [comment]
Elom KOSSI

https://github.com/ElomKossi/GL51.P2020/pull/2

**Comment by jinhogate** [comment]
GBEGNON Kossi
https://github.com/jinhogate/p2020/pull/3

**Comment by Zechirine** [comment]
Nouassi Zechirine
https://github.com/Zechirine/GL51_p20/pull/1

**Comment by yamineben** [comment]
BENMESSAOUD Yamine
Test avec mock du MovieClient : https://github.com/yamineben/GL51-TD3/blob/MovieController/src/test/groovy/gl51/MovieControllerSpec.groovy
Pull request : https://github.com/yamineben/GL51-TD3/pull/1

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
Merge request : https://github.com/nzodalandry/GL51_PROJECT_TD3/pull/1

**Comment by Gresefo** [comment]
Loïc MARTIN
Merge request : https://github.com/Gresefo/TD4/pull/1

**Comment by kAgotsi** [comment]
Gédéon AGOTSI
Merge request : https://github.com/kAgotsi/gl51-tp1/pull/2

**Comment by HaoyunLIAO** [comment]
HaoyunLIAO
Merge request :https://github.com/HaoyunLIAO/GL51-TD3/pull/1

**Comment by BaiYuhaoSpiceeYJ** [comment]
BAI YUHAO
https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/pull/1

**Comment by LPA2-Automne2016** [comment]
fin du délai

**Comment by ZhanKanyun** [comment]
ZHAN Kanyun
Merge request :https://github.com/ZhanKanyun/TD3_GL51/pull/3

**Comment by bdaris** [comment]
Nanjeu Borel Daris
https://github.com/bdaris/GL51Groovy/pull/2
