### ISSUE TITLE
finaliser le project

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#8]
Rendre une merge request avec:

- la validation des tests de votre code
- codenarc mis en place
- codefactor activé sur le projet ( et une note de A+ )
- le README.md créé avec les 2 badges github action + code factor

**Comment by EleryanYuri** [comment]
Aurélien Saunier
Merge request : https://github.com/EleryanYuri/GL51_TD1/pull/2

**Comment by stanicchris** [comment]
STANIC-PAGANO Christopher
Merge request: https://github.com/stanicchris/Projet_GL51/pull/3

**Comment by ElomKossi** [comment]
Elom KOSSI
La Merge Request: https://github.com/ElomKossi/GL51.P2020/pull/3

**Comment by ZilinGUO** [comment]
GUO Zilin
La Merge Request: https://github.com/ZilinGUO/GL51_TD5/pull/1

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie
Merge Request: https://github.com/PmRay/gl51/pull/1

**Comment by yamineben** [comment]
BENMESSAOUD Yamine
Merge Request : https://github.com/yamineben/GL51-TD3/pull/1

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
Merge Request : https://github.com/nzodalandry/GL51_PROJECT_TD3/pull/1

**Comment by AntoineYu** [comment]
Yu ZhenQing
Merge Request : https://github.com/AntoineYu/GL51_TD4/pull/1

**Comment by patricke25** [comment]
PEGON Sylvain
https://github.com/patricke25/GL51_TD1/pull/8

**Comment by Zechirine** [comment]
Nouassi Zechirine
Merge Request : https://github.com/Zechirine/GL51_p20/pull/1

**Comment by zhuoli-wu** [comment]
WU Zhuoli
Merge Request: https://github.com/zhuoli-wu/GL51_TD2/pull/1

**Comment by CharlotteYU** [comment]
Shijia YU
Merge Request : https://github.com/CharlotteYU/GL51TD/pull/1

**Comment by desperadooo** [comment]
ZHENG Huangkai
Merge Request : https://github.com/desperadooo/GL51_TD3/pull/2

**Comment by YvetteMiao** [comment]
Yiwen MIAO
Merge Request : https://github.com/YvetteMiao/p2020/pull/2

**Comment by MaoJiawei97** [comment]
Mao Jiawei
Merge Request: https://github.com/MaoJiawei97/GL51_TD4/pull/1

**Comment by BaiYuhaoSpiceeYJ** [comment]
BAI Yuhao
Merge Request:https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/pull/1
Project:https://github.com/BaiYuhaoSpiceeYJ/GL51-TD3/tree/branche2

**Comment by Grudging7645** [comment]
BONNETAIN Camille
Merge request : https://github.com/camille-bonnetain/gl51/pull/2

**Comment by bdaris** [comment]
NANJEU Borel Daris

Github avec le readme: https://github.com/bdaris/GL51Groovy

La merge request: https://github.com/bdaris/GL51Groovy/commit/a842f4cc471e0ac3efbbdf915596bda8c95a48d3

Mon gradle check: j'ai pas le même fichier gradle parce j'ai adapté pour fonctionner avec windows et je l'ai mis dans le dossier parent de mon projet p2020 en l'occurence GL51Groovy mais il fonctionne bien pour faire mes CI. 
https://github.com/bdaris/GL51Groovy/blob/master/.github/workflows/gradle.yml

**Comment by HaoyunLIAO** [comment]
LIAO Haoyun
Merge Request :https://github.com/HaoyunLIAO/GL51-TD3/pull/1/

**Comment by Hawlink** [comment]
SIDAWY Cem
Merge request : https://github.com/Hawlink/GL51TD1/pull/3

**Comment by jinhogate** [comment]
GBEGNON KOSSI
https://github.com/jinhogate/p2020/pull/3

**Comment by kAgotsi** [comment]
Gédéon AGOTSI
Merge request : https://github.com/kAgotsi/gl51-tp1/pull/5

**Comment by ZhanKanyun** [comment]
ZHAN Kanyun
Merge request: https://github.com/ZhanKanyun/TD3_GL51/pull/4
