### ISSUE TITLE
mettre en place l'intégration continue avec Cypress et le dashboard de cypress

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/gl51-P2020#9]
Mettre en  place l'intégration continue via github actions
remonter les données dans le dashboard cypress

publier ici le lien vers github actions et le lien vers le dashboard cypress.

**Comment by yamineben** [comment]
BENMESSAOUD Yamine
Action : https://github.com/yamineben/cypress_test/actions/runs/80868898
Dashboard : https://dashboard.cypress.io/projects/mdunv8/runs/3/specs

**Comment by ZilinGUO** [comment]
ZILIN GUO
Action : https://github.com/ZilinGUO/cypress/actions
Dashboard : https://dashboard.cypress.io/projects/susek4/runs/2/specs

**Comment by desperadooo** [comment]
ZHENG Huangkai
Action : https://github.com/desperadooo/cypress-p2020/actions
Dashboard : https://dashboard.cypress.io/projects/sgui7j/runs/1/specs

**Comment by zhuoli-wu** [comment]
WU Zhuoli
Action：https://github.com/zhuoli-wu/cypress/actions
Dashboard：https://dashboard.cypress.io/projects/i88nnt/runs/2/specs

**Comment by EleryanYuri** [comment]
Aurélien SAUNIER
Action : https://github.com/EleryanYuri/cypressTest/actions/runs/80858365
Cypress dashboard : https://dashboard.cypress.io/projects/rc59o3/runs/2/specs

**Comment by AntoineYu** [comment]
Yu ZhenQing
Action: https://github.com/AntoineYu/cypress_test/actions/runs/80974008
Cypress dashboard: https://dashboard.cypress.io/projects/4kuqau/runs/1/specs

**Comment by patricke25** [comment]
PEGON Sylvain
Action : https://github.com/patricke25/cypress/actions/runs/80976931
Dashboard : https://dashboard.cypress.io/projects/544vi7/runs/1/specs

**Comment by YvetteMiao** [comment]
Yiwen MIAO
Action : https://github.com/YvetteMiao/cypress-gl51/actions
Dashboard :https://dashboard.cypress.io/projects/5x2azq/runs/4/specs

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
Action : https://github.com/yamineben/cypress_test/actions/runs/80853250
Dashboard : https://dashboard.cypress.io/projects/b7npq2/runs/2/specs

**Comment by nzodalandry** [comment]
NZODA OUMBE Landry
Action : https://github.com/nzodalandry/CYPRESS_TEST/actions/runs/81099318
Dashboard : https://dashboard.cypress.io/projects/b7npq2/runs/2/specs

**Comment by ElomKossi** [comment]
KOSSI Elom 

Action: https://github.com/ElomKossi/cypress_test/actions/runs/84253479
Dashboard: https://dashboard.cypress.io/projects/69kg16/runs/1/specs

**Comment by Zechirine** [comment]
NOUASSI Zechirine

Action: https://github.com/Zechirine/Cypress_Project/actions/runs/84286228
Dashboard : https://dashboard.cypress.io/projects/bmhmi9/runs/1/specs

**Comment by stanicchris** [comment]
STANIC-PAGANO Christopher

action: https://github.com/stanicchris/cypress/actions/runs/84745619
dashboard: https://dashboard.cypress.io/projects/399sd1/runs/5/specs

**Comment by jinhogate** [comment]
GBEGNON kossi 
action: https://github.com/jinhogate/cypress_p2020/actions
dashboard: https://dashboard.cypress.io/projects/fnp5r2/runs/1/specs

**Comment by bdaris** [comment]
NANJEU Borel Daris

https://github.com/bdaris/cypress-gl51/actions/runs/85385198

https://dashboard.cypress.io/projects/wmgxf3/runs/3/specs

**Comment by kAgotsi** [comment]
Gédéon AGOTSI
action : https://github.com/kAgotsi/cypress_test/actions/runs/85802725
dashboard : https://dashboard.cypress.io/projects/y6oa9d/runs/1/specs

**Comment by Hawlink** [comment]
SIDAWY Cem
Action : https://github.com/Hawlink/cypresstesting/actions/runs/85801029
Dashboard : https://dashboard.cypress.io/projects/xojjck/runs/3/specs

**Comment by CharlotteYU** [comment]
Shijia YU
Action: https://github.com/CharlotteYU/GL51_cypress/actions
Dashboard: https://dashboard.cypress.io/projects/4hdhtn/runs/1/specs

**Comment by MaoJiawei97** [comment]
Mao Jiawei
Action:https://github.com/MaoJiawei97/Cypress_td/actions/runs/85929317
Dashboard: https://dashboard.cypress.io/projects/6tsjnv/runs/1/specs

**Comment by HaoyunLIAO** [comment]
Haoyun LIAO
Action : https://github.com/HaoyunLIAO/cypress-2020/actions/runs/86131452
Cypress dashboard : https://dashboard.cypress.io/projects/i4mk3m/runs/3/specs

**Comment by BaiYuhaoSpiceeYJ** [comment]
BAI YUHAO
Action : https://github.com/BaiYuhaoSpiceeYJ/cypress_test/actions/runs/86139622
Dashboard: https://dashboard.cypress.io/projects/a84rg2/runs/1/specs

**Comment by Grudging7645** [comment]
BONNETAIN Camille
Action : https://github.com/camille-bonnetain/cypress-test/actions/runs/86138042
Dashboard : https://dashboard.cypress.io/projects/j1d1xo/runs/1/specs

**Comment by PmRay** [comment]
FANTCHENOU Pierre-Marie

Action: https://github.com/PmRay/Cypress/actions/runs/86299103
Dashboard: https://dashboard.cypress.io/projects/8cpwu6/runs/4/specs

**Comment by ZhanKanyun** [comment]
ZHAN Kanyun 

Action: https://github.com/ZhanKanyun/Cypress-Test/actions/runs/86683302
Dashboard: https://dashboard.cypress.io/projects/zw1237/runs/1/specs
